REM @%YOUR_NETWORD_NAME%: you name it
REM @%YOUR_DB_NAME%: ClickHouse DB name
REM @%YOUR_DB_USER_NAME%: ClickHouse DB user
REM @%YOUR_DB_PASSWORD%: ClickHouse DB password
REM @%YOUR_MOUNT_PATH%: path of 'tensorzero.toml' on your local
REM @%AZURE_SERVICE_KEY%: get it from Azure Portal
SET YOUR_NETWORD_NAME=<FILL_BEFORE_USE>
SET YOUR_DB_NAME=<FILL_BEFORE_USE>
SET YOUR_DB_USER_NAME=<FILL_BEFORE_USE>
SET YOUR_DB_PASSWORD=<FILL_BEFORE_USE>
SET YOUR_MOUNT_PATH=%cd%/config
SET AZURE_SERVICE_KEY=<FILL_BEFORE_USE>
